import { createApp } from 'vue'
import {
  create,
  NAlert,
  NButton,
  NCard,
  NCheckbox,
  NConfigProvider,
  NDataTable,
  NDescriptions,
  NDescriptionsItem,
  NDivider,
  NDrawer,
  NDrawerContent,
  NEmpty,
  NEllipsis,
  NForm,
  NFormItem,
  NGradientText,
  NIcon,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutSider,
  NList,
  NListItem,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPopconfirm,
  NPagination,
  NProgress,
  NRadioButton,
  NRadioGroup,
  NScrollbar,
  NSelect,
  NSkeleton,
  NSlider,
  NSpace,
  NSpin,
  NStatistic,
  NSwitch,
  NTag,
  NThing,
  darkTheme,
} from 'naive-ui'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './style.css'

const naive = create({
  components: [
    NAlert,
    NButton,
    NCard,
    NCheckbox,
    NConfigProvider,
    NDataTable,
    NDescriptions,
    NDescriptionsItem,
    NDivider,
    NDrawer,
    NDrawerContent,
    NEmpty,
    NEllipsis,
    NForm,
    NFormItem,
    NGradientText,
    NIcon,
    NInput,
    NInputNumber,
    NLayout,
    NLayoutContent,
    NLayoutSider,
    NList,
    NListItem,
    NMessageProvider,
    NModal,
    NNotificationProvider,
    NPopconfirm,
    NPagination,
    NProgress,
    NRadioButton,
    NRadioGroup,
    NScrollbar,
    NSelect,
    NSkeleton,
    NSlider,
    NSpace,
    NSpin,
    NStatistic,
    NSwitch,
    NTag,
    NThing,
  ],
})

createApp(App)
  .provide('naiveTheme', darkTheme)
  .use(createPinia())
  .use(router)
  .use(naive)
  .mount('#app')
